#!/usr/bin/env bash
set -uo pipefail

# capture-defaults.sh — read the CURRENT machine's macOS preferences for a
# curated vocabulary of settings and print them as ready-to-review
# `defaults write` lines (and `dockutil --add` lines for the Dock).
#
# This is a DISCOVERY aid, not a Provisioning script: it never writes anything.
# The workflow is deliberately human-in-the-loop and matches the "minimal
# deterministic core" philosophy (ADR-0009):
#
#   1. Change a setting in System Settings.
#   2. Run `bash scripts/capture-defaults.sh` (optionally `| grep -i mouse`).
#   3. Copy the emitted line(s) into `home/run_onchange_after_20-macos-defaults.sh`
#      (or the Dock into `home/run_onchange_after_30-dock.sh`), then `chezmoi apply`.
#
# Only keys in the curated list below are read — `defaults` domains hold far more
# noise than is worth versioning. Add a `domain|key` pair to grow the vocabulary.
# Type (bool/int/float/string) is auto-detected, so you only maintain the keys.

# emit <domain> <key> — print a `defaults write` line for the current value,
# or a commented "(unset)" marker if the key is not currently set.
emit() {
  local domain="$1" key="$2" type value flag
  if ! type=$(defaults read-type "$domain" "$key" 2>/dev/null); then
    printf '#   (unset)  %s "%s"\n' "$domain" "$key"
    return
  fi
  value=$(defaults read "$domain" "$key" 2>/dev/null)
  case "$type" in
    "Type is boolean") flag="-bool";   [ "$value" = "1" ] && value="true" || value="false" ;;
    "Type is integer") flag="-int" ;;
    "Type is float")   flag="-float" ;;
    "Type is string")  flag="-string" ;;
    *) printf '#   (complex: %s) inspect with: defaults read %s "%s"\n' "$type" "$domain" "$key"; return ;;
  esac
  printf 'defaults write %s "%s" %s "%s"\n' "$domain" "$key" "$flag" "$value"
}

# section <title> <domain|key>... — print a header then one emit per pair.
section() {
  local title="$1"; shift
  printf '\n# --- %s %s\n' "$title" "$(printf '#%.0s' $(seq 1 $((60 - ${#title}))))"
  local pair
  for pair in "$@"; do
    emit "${pair%%|*}" "${pair#*|}"
  done
}

printf '# macOS defaults captured from this machine — review, then paste into\n'
printf '# home/run_onchange_after_20-macos-defaults.sh. Generated by scripts/capture-defaults.sh.\n'

section "Input — mouse, trackpad speed & scroll" \
  "NSGlobalDomain|com.apple.mouse.scaling" \
  "NSGlobalDomain|com.apple.scrollwheel.scaling" \
  "NSGlobalDomain|com.apple.trackpad.scaling" \
  "NSGlobalDomain|com.apple.swipescrolldirection"

section "Keyboard" \
  "NSGlobalDomain|KeyRepeat" \
  "NSGlobalDomain|InitialKeyRepeat" \
  "NSGlobalDomain|AppleKeyboardUIMode" \
  "NSGlobalDomain|ApplePressAndHoldEnabled" \
  "NSGlobalDomain|NSAutomaticSpellingCorrectionEnabled" \
  "NSGlobalDomain|NSAutomaticCapitalizationEnabled"

section "Appearance & sound" \
  "NSGlobalDomain|AppleInterfaceStyle" \
  "NSGlobalDomain|AppleShowScrollBars" \
  "NSGlobalDomain|com.apple.sound.beep.feedback"

# Trackpad gestures live in TWO domains (built-in vs Bluetooth); capture both.
for td in com.apple.AppleMultitouchTrackpad com.apple.driver.AppleBluetoothMultitouch.trackpad; do
  section "Trackpad gestures ($td)" \
    "$td|Clicking" \
    "$td|TrackpadThreeFingerDrag" \
    "$td|TrackpadRightClick" \
    "$td|TrackpadTwoFingerDoubleTapGesture" \
    "$td|TrackpadThreeFingerHorizSwipeGesture" \
    "$td|TrackpadThreeFingerVertSwipeGesture" \
    "$td|TrackpadFourFingerHorizSwipeGesture" \
    "$td|TrackpadFourFingerVertSwipeGesture" \
    "$td|TrackpadFourFingerPinchGesture" \
    "$td|TrackpadPinch" \
    "$td|TrackpadRotate" \
    "$td|TrackpadTwoFingerFromRightEdgeSwipeGesture"
done

section "Dock — sizing, effects, gestures" \
  "com.apple.dock|tilesize" \
  "com.apple.dock|magnification" \
  "com.apple.dock|largesize" \
  "com.apple.dock|show-recents" \
  "com.apple.dock|mineffect" \
  "com.apple.dock|autohide" \
  "com.apple.dock|orientation" \
  "com.apple.dock|showAppExposeGestureEnabled" \
  "com.apple.dock|showLaunchpadGestureEnabled" \
  "com.apple.dock|showMissionControlGestureEnabled"

section "Finder" \
  "com.apple.finder|NewWindowTarget" \
  "com.apple.finder|ShowExternalHardDrivesOnDesktop" \
  "com.apple.finder|ShowRecentTags" \
  "com.apple.finder|FXDefaultSearchScope" \
  "com.apple.finder|ShowPathbar" \
  "com.apple.finder|ShowStatusBar" \
  "com.apple.finder|FXPreferredViewStyle"

section "Menu bar & privacy" \
  "com.apple.controlcenter|NSStatusItem Visible Bluetooth" \
  "com.apple.AdLib|allowApplePersonalizedAdvertising"

# --- Dock layout -----------------------------------------------------------
printf '\n# --- Dock layout (paste into home/run_onchange_after_30-dock.sh) %s\n' "$(printf '#%.0s' $(seq 1 10))"
if command -v dockutil >/dev/null 2>&1; then
  # dockutil --list is tab-separated: name<TAB>file-URL<TAB>...  Convert the
  # URL column back to a filesystem path and emit an --add line per app.
  dockutil --list 2>/dev/null | while IFS=$'\t' read -r name url _rest; do
    [ -z "${url:-}" ] && continue
    path=$(python3 -c 'import sys,urllib.parse;print(urllib.parse.unquote(sys.argv[1]))' "${url#file://}" 2>/dev/null)
    path="${path%/}"
    printf 'dockutil --no-restart --add "%s"   # %s\n' "$path" "$name"
  done
else
  printf '# dockutil not installed — skipping Dock capture.\n'
fi
